### ISSUE TITLE
Server Closed

### ISSUE THREAD

**Issue by OxBrutal** [AraaCuteUwU/Playerwarp#2]
* Idk, you can see it in the log below
[Thu_Aug_18-02.56.34-UTC_2022.log](https://github.com/AraaCuteUwU/Playerwarp/files/9367646/Thu_Aug_18-02.56.34-UTC_2022.log)

**Comment by AraaCuteUwU** [comment]
> * Idk, you can see it in the log below
>   [Thu_Aug_18-02.56.34-UTC_2022.log](https://github.com/AraaCuteUwU/Playerwarp/files/9367646/Thu_Aug_18-02.56.34-UTC_2022.log)

Try to use /pwarp info <name>
